# Generated by Django 4.1.7 on 2023-04-13 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
